# Generated by Django 5.1.6 on 2025-03-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_staffuser_le_remove_staffuser_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('mobileuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.mobileuser')),
                ('position', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('users.mobileuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('mobileuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.mobileuser')),
                ('class_number', models.IntegerField(choices=[(1, 'Class A'), (2, 'Class B'), (3, 'Class C')], default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('users.mobileuser',),
        ),
    ]
